import type { Question } from "../types/question.types";
import { option } from "./question-option";

const yesLifeCover = ["yes_nem", "yes_other", "yes_employer"];

export const currentCoverQuestions: Question[] = [
  {
    id: "location",
    version: 1,
    section: "location",
    title: "Where do you currently live or operate from?",
    whyWeAsk:
      "Location can affect the type of protection that may be relevant, especially for health access, property, business, flooding, and travel-related risks.",
    helperText: "State and city/LGA only. Please do not enter an exact address.",
    type: "location_select",
    required: true,
    scoringTags: ["location_context"],
    recommendationTags: ["health_access", "property_risk"],
    privacyLevel: "moderate",
    sensitivity: "moderate",
    analyticsKey: "question_location",
    adminLabel: "LOCATION_CONTEXT",
    customerLabel: "State and city/LGA",
    displayOrder: 50,
    isActive: true,
  },
  {
    id: "location_risk_context",
    version: 1,
    section: "location",
    title: "Do you live, work, or own property in an area affected by any of these?",
    whyWeAsk:
      "This helps keep property and business protection suggestions relevant without asking for an exact address.",
    type: "multi_choice",
    required: false,
    allowNotSure: true,
    options: [
      option("flooding", "Flooding", 10),
      option("fire_risk", "Fire risk", 20),
      option("theft_burglary", "Theft or burglary concerns", 30),
      option("business_disruption", "Business disruption", 40),
      option("not_sure", "I am not sure", 50),
      option("none", "None of these", 60),
    ],
    scoringTags: ["location_risk"],
    recommendationTags: ["property_business"],
    privacyLevel: "moderate",
    sensitivity: "moderate",
    analyticsKey: "question_location_risk_context",
    adminLabel: "LOCATION_RISK_CONTEXT",
    customerLabel: "Location risk context",
    displayOrder: 60,
    isActive: true,
  },
  {
    id: "existing_life_cover",
    version: 1,
    section: "current_cover",
    title: "Do you currently have life insurance?",
    whyWeAsk: "This helps estimate whether your family may already have some financial protection.",
    type: "single_choice",
    required: true,
    allowNotSure: true,
    options: [
      option("yes_nem", "Yes, with NEM", 10, { followUpQuestionIds: ["life_cover_range"] }),
      option("yes_other", "Yes, with another insurer", 20, {
        followUpQuestionIds: ["life_cover_range"],
      }),
      option("yes_employer", "Yes, through my employer", 30, {
        followUpQuestionIds: ["life_cover_range"],
        adminLabel: "GROUP_LIFE_DECLARED",
      }),
      option("no", "No", 40),
      option("not_sure", "I am not sure", 50),
    ],
    scoringTags: ["life_cover"],
    recommendationTags: ["life_cover"],
    privacyLevel: "low",
    sensitivity: "low",
    analyticsKey: "question_existing_life_cover",
    adminLabel: "EXISTING_LIFE_COVER",
    customerLabel: "Existing life cover",
    displayOrder: 70,
    isActive: true,
  },
  {
    id: "life_cover_range",
    version: 1,
    section: "current_cover",
    title: "About how much cover do you have?",
    whyWeAsk:
      "This helps estimate coverage level using ranges only, without policy numbers or documents.",
    helperText: "A broad range is enough. Please do not enter a policy number.",
    type: "range_select",
    required: true,
    allowNotSure: true,
    options: [
      option("below_1m", "Less than N1m", 10),
      option("1m_5m", "N1m-N5m", 20),
      option("5m_10m", "N5m-N10m", 30),
      option("10m_25m", "N10m-N25m", 40),
      option("above_25m", "Above N25m", 50),
      option("not_sure", "I am not sure", 60),
      option("prefer_not_say", "I prefer not to say", 70),
    ],
    scoringTags: ["life_cover_range"],
    recommendationTags: ["life_cover"],
    privacyLevel: "moderate",
    sensitivity: "moderate",
    analyticsKey: "question_life_cover_range",
    adminLabel: "LIFE_COVER_RANGE",
    customerLabel: "Life cover range",
    displayOrder: 80,
    isActive: true,
    dependsOn: {
      mode: "any",
      conditions: yesLifeCover.map((optionId) => ({
        questionId: "existing_life_cover",
        operator: "includes_option",
        optionId,
      })),
    },
  },
  {
    id: "monthly_protection_comfort",
    version: 1,
    section: "current_cover",
    title: "How much can you comfortably set aside monthly for family protection?",
    whyWeAsk:
      "Budget ranges help future modules suggest realistic next steps without asking for salary.",
    helperText:
      "This is not a payment request. It only helps estimate what kind of plan may fit your budget.",
    type: "range_select",
    required: true,
    options: [
      option("below_5000", "Below N5,000", 10),
      option("5000_10000", "N5,000-N10,000", 20),
      option("10000_25000", "N10,000-N25,000", 30),
      option("25000_50000", "N25,000-N50,000", 40),
      option("above_50000", "Above N50,000", 50),
      option("need_guidance", "I need guidance", 60),
    ],
    scoringTags: ["budget_range"],
    recommendationTags: ["budget_fit"],
    privacyLevel: "moderate",
    sensitivity: "moderate",
    analyticsKey: "question_monthly_protection_comfort",
    adminLabel: "MONTHLY_PROTECTION_COMFORT",
    customerLabel: "Monthly protection comfort",
    displayOrder: 90,
    isActive: true,
  },
];
