import type { Question } from "../types/question.types";
import { option } from "./question-option";

const yesDependents = ["yes", "sometimes", "not_sure"];

export const familyQuestions: Question[] = [
  {
    id: "soft_personalization",
    version: 1,
    section: "about_you",
    title: "What should we call you?",
    shortTitle: "Your name",
    helperText: "We will use this to personalize your result.",
    type: "text",
    required: false,
    skippable: true,
    validation: { maxLength: 40 },
    scoringTags: [],
    recommendationTags: [],
    privacyLevel: "low",
    sensitivity: "low",
    analyticsKey: "question_soft_personalization",
    adminLabel: "SOFT_PERSONALIZATION",
    customerLabel: "Preferred name",
    displayOrder: 10,
    isActive: true,
  },
  {
    id: "protection_intent",
    version: 1,
    section: "family",
    title: "Who are you mainly trying to protect?",
    whyWeAsk: "This helps us understand what kind of protection matters most to you.",
    type: "single_choice",
    required: true,
    allowNotSure: true,
    options: [
      option("spouse", "My spouse", 10, { tags: ["family_intent"] }),
      option("children", "My children", 20, { tags: ["dependency_signal"] }),
      option("parents", "My parents", 30, { tags: ["dependency_signal"] }),
      option("business", "My business", 40, { tags: ["business_signal"] }),
      option("myself", "Myself", 50, { tags: ["protection_goal"] }),
      option("not_sure", "I am not sure yet", 60, { tags: ["not_sure"] }),
    ],
    scoringTags: ["protection_goal"],
    recommendationTags: ["family_intent", "dependency_signal"],
    privacyLevel: "low",
    sensitivity: "low",
    analyticsKey: "question_protection_intent",
    adminLabel: "PROTECTION_INTENT",
    customerLabel: "Protection intent",
    displayOrder: 20,
    isActive: true,
  },
  {
    id: "financial_dependents",
    version: 1,
    section: "family",
    title: "Do people currently depend on your income or support?",
    whyWeAsk:
      "This helps estimate how important life cover, health protection, and emergency planning may be for your family.",
    type: "single_choice",
    required: true,
    allowNotSure: true,
    options: [
      option("yes", "Yes", 10, { followUpQuestionIds: ["dependent_count"] }),
      option("no", "No", 20),
      option("sometimes", "Sometimes", 30, { followUpQuestionIds: ["dependent_count"] }),
      option("not_sure", "I am not sure", 40, { followUpQuestionIds: ["dependent_count"] }),
    ],
    scoringTags: ["dependents"],
    recommendationTags: ["life_cover", "health_cover"],
    privacyLevel: "low",
    sensitivity: "low",
    analyticsKey: "question_financial_dependents",
    adminLabel: "FINANCIAL_DEPENDENTS",
    customerLabel: "Financial dependents",
    displayOrder: 30,
    isActive: true,
  },
  {
    id: "dependent_count",
    version: 1,
    section: "family",
    title: "How many people depend on you financially?",
    type: "range_select",
    required: true,
    options: ["0", "1", "2-3", "4-5", "More than 5"].map((label, index) =>
      option(label.toLowerCase().replaceAll(" ", "_"), label, (index + 1) * 10),
    ),
    scoringTags: ["dependent_count"],
    recommendationTags: ["life_cover"],
    privacyLevel: "low",
    sensitivity: "low",
    analyticsKey: "question_dependent_count",
    adminLabel: "DEPENDENT_COUNT",
    customerLabel: "Dependent count",
    displayOrder: 40,
    isActive: true,
    dependsOn: {
      mode: "any",
      conditions: yesDependents.map((optionId) => ({
        questionId: "financial_dependents",
        operator: "includes_option",
        optionId,
      })),
    },
  },
];
