import type { Question } from "../types/question.types";
import { option } from "./question-option";

export const readinessAndOtherQuestions: Question[] = [
  {
    id: "professional_business_risk",
    version: 1,
    section: "property_business",
    title:
      "Do people or clients depend on your professional service, advice, or business operations?",
    whyWeAsk:
      "This helps identify whether business protection, professional indemnity, or staff-related protection may be relevant.",
    type: "single_choice",
    required: true,
    allowNotSure: true,
    options: [
      option("run_business", "Yes, I run a business", 10),
      option("professional_services", "Yes, I provide professional services", 20),
      option("employ_staff", "Yes, I employ staff", 30),
      option("no", "No", 40),
      option("not_sure", "I am not sure", 50),
    ],
    scoringTags: ["business_risk"],
    recommendationTags: ["business_cover", "professional_indemnity"],
    privacyLevel: "low",
    sensitivity: "low",
    analyticsKey: "question_professional_business_risk",
    adminLabel: "PROFESSIONAL_BUSINESS_RISK",
    customerLabel: "Professional or business risk",
    displayOrder: 140,
    isActive: true,
  },
  {
    id: "beneficiary_readiness",
    version: 1,
    section: "readiness",
    title: "If something happens, are your beneficiaries or next of kin up to date?",
    whyWeAsk:
      "Beneficiary readiness can help your family avoid confusion later without sharing names here.",
    helperText:
      "You do not need to enter beneficiary details here. This only helps check your readiness.",
    type: "single_choice",
    required: true,
    allowNotSure: true,
    options: [
      option("yes", "Yes", 10),
      option("no", "No", 20),
      option("not_sure", "I am not sure", 30),
      option("never_set_up", "I have never set this up", 40),
    ],
    scoringTags: ["beneficiary_readiness"],
    recommendationTags: ["beneficiary_review"],
    privacyLevel: "moderate",
    sensitivity: "moderate",
    analyticsKey: "question_beneficiary_readiness",
    adminLabel: "BENEFICIARY_READINESS",
    customerLabel: "Beneficiary readiness",
    displayOrder: 150,
    isActive: true,
  },
  {
    id: "document_readiness",
    version: 1,
    section: "readiness",
    title: "Do you know where your important family documents are kept?",
    helperText: "No upload is needed for this check.",
    type: "single_choice",
    required: true,
    options: [
      option("organized", "Yes, organized", 10),
      option("some", "Some are organized", 20),
      option("not_really", "Not really", 30),
      option("need_help", "I need help with this", 40),
    ],
    scoringTags: ["document_readiness"],
    recommendationTags: ["family_readiness"],
    privacyLevel: "low",
    sensitivity: "low",
    analyticsKey: "question_document_readiness",
    adminLabel: "DOCUMENT_READINESS",
    customerLabel: "Document readiness",
    displayOrder: 160,
    isActive: true,
  },
  {
    id: "external_insurance_elsewhere",
    version: 1,
    section: "other_cover",
    title: "Do you currently have insurance with another company?",
    whyWeAsk:
      "This keeps future recommendations balanced without asking for policy numbers or login details.",
    type: "single_choice",
    required: true,
    allowNotSure: true,
    options: [
      option("yes", "Yes", 10, { followUpQuestionIds: ["external_insurance_categories"] }),
      option("no", "No", 20),
      option("not_sure", "I am not sure", 30),
      option("prefer_not_say", "I prefer not to say", 40),
    ],
    scoringTags: ["external_cover"],
    recommendationTags: ["cross_sell_context"],
    privacyLevel: "moderate",
    sensitivity: "moderate",
    analyticsKey: "question_external_insurance_elsewhere",
    adminLabel: "EXTERNAL_INSURANCE_ELSEWHERE",
    customerLabel: "Insurance elsewhere",
    displayOrder: 170,
    isActive: true,
  },
  {
    id: "external_insurance_categories",
    version: 1,
    section: "other_cover",
    title: "Which type of cover do you already have elsewhere?",
    whyWeAsk:
      "Categories are enough for this check. Please do not enter policy numbers or upload documents.",
    type: "multi_choice",
    required: false,
    options: [
      "Life",
      "Health",
      "Motor",
      "Home",
      "Fire",
      "Business",
      "Travel",
      "Professional indemnity",
      "Other",
      "I prefer not to say",
    ].map((label, index) =>
      option(label.toLowerCase().replaceAll(" ", "_"), label, (index + 1) * 10),
    ),
    scoringTags: ["external_cover_categories"],
    recommendationTags: ["cross_sell_context"],
    privacyLevel: "moderate",
    sensitivity: "moderate",
    analyticsKey: "question_external_insurance_categories",
    adminLabel: "EXTERNAL_INSURANCE_CATEGORIES",
    customerLabel: "External insurance categories",
    displayOrder: 180,
    isActive: true,
    dependsOn: {
      mode: "all",
      conditions: [
        {
          questionId: "external_insurance_elsewhere",
          operator: "includes_option",
          optionId: "yes",
        },
      ],
    },
  },
];
